# Generated by Django 4.0.2 on 2022-07-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_avis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avis',
        ),
    ]
