# Generated by Django 4.0.2 on 2022-07-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_avis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('DOB', models.DateField(null=True)),
                ('bio', models.CharField(max_length=120)),
            ],
        ),
    ]
